#!/bin/bash

sudo su
apt-get update
apt-get upgrade -y
apt install bettercap -y
apt install fonts-nanum -y 
apt install fcitx-lib* -y
apt install fcitx-hangul -y 
apt install terminator -y

mkdir /usr/local/share/bettercap
mkdir /usr/local/share/bettercap/caplets
cp -r hstshijack /usr/local/share/bettercap/caplets
cp spoof.cap ~

cd ~
git clone https://github.com/arismelachroinos/lscript.git
cd lscript
chmod +x install.sh
./install.sh
cp l /bin

cd ~
rm -r kali_set